version: '2'

services:
  frontend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      # TODO: change this mapping to map the port your application listens on
      - 3200:3200
